### ISSUE TITLE
(meta) Base template

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/hacker-houses-streams#9]
Make a white-label / forkable main branch.

- [x] Fix contract (reverted on read)
- [x] Fix fron-end (unique members, hide cap = 0)
- [x] Base style (no rainbow colors :D)
- [x] Split index.tsx logic into components
- [ ] Good Readme
- [ ] More base features?

**Comment by Pabl0cks** [comment]
> Base style (no rainbow colors :D)

@carletex Could be something like that? I just did a cleanup of the bg-hacker styles for now. I've created PR #10 with those changes.

![image](https://github.com/BuidlGuidl/hacker-houses-streams/assets/55535804/f9719113-165e-481a-a0a5-6bf4b343ce1a)
